### ISSUE TITLE
How does UI control jump to dialing interface?

### ISSUE THREAD

**Issue by lokihard** [cisco-ce/roomos.cisco.com#1]

**Comment by lokihard** [comment]
@tbjolset This function can be realized?
![image](https://user-images.githubusercontent.com/26132345/118099927-76c08a80-b408-11eb-8519-846e2418dc65.png)

**Comment by tbjolset** [comment]
Hi lokihard, yes this can be implemented with a listener on the ui extension button in a macro
https://roomos.cisco.com/xapi/Event.UserInterface.Extensions.Widget.Action
that then opens a custom dialog:
https://roomos.cisco.com/xapi/Command.UserInterface.Message.Prompt.Display/

**Comment by lokihard** [comment]
> 嗨，lokihard，是的，可以使用侦听器在宏
> https://roomos.cisco.com/xapi/Event.UserInterface.Extensions.Widget.Action的ui扩展按钮上实现
> ，然后打开一个自定义对话框：
> [https：/ /roomos.cisco.com/xapi/Command.UserInterface.Message.Prompt.Display/](https://roomos.cisco.com/xapi/Command.UserInterface.Message.Prompt.Display/)

**Comment by lokihard** [comment]
Hi tbjolset, For this function is not implemented on ce9.15, whether it does not support CE, and whether it can give an example, I have difficulties here. Thank you very much.

**Comment by lokihard** [comment]
@tbjolset Hi tbjolset, For this function is not implemented on ce9.15, whether it does not support CE, and whether it can give an example, I have difficulties here. Thank you very much.

**Comment by tbjolset** [comment]
@lokihard , this works well on all version of CE9, as long as you are not on a SX10. please see https://roomos.cisco.com/docs/Macro/Tutorial.md to learn basic xapi and javascript programming. Unfortunately we are not in a position to make macros for people on demand.

**Comment by lokihard** [comment]
thank you
